services:
  tele-cloud:
    build:
      context: .
      dockerfile: Dockerfile
    image: tele-cloud
    container_name: tele-cloud
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./metadata:/app/metadata
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s